name: Build TSP Visualizer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: jdk/mise-action@v2

      - name: Build with Maven
        run: mvn -B package --file pom.xml
